In [1]:
# Install required python packages
!pip install pandas==1.3.5
!pip install xport==2.0.2

Collecting pandas==1.3.5
  Downloading pandas-1.3.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 28.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.5) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 1.9.0 requires pandas>=1.5.0, but you have pandas 1.3.5 which is incompatible.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.3.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 1.3.5 which is incompatible.
plotnine 0.12.4 requires pandas>=1.5.0, but you have pandas 1.3.5 which is incompatible.
statsmodels 0.14.2 requires pandas!=2.1.0,>=1.4, but you have pandas 1.3.5 which is incompatible.
xarray 2023.7.0 requires pandas>=1.4, but you have pandas 1.3.5 which is incompatible.
Successfully installed pandas-1.3.5
Collecting xport==2.0.2
  Downloading xport-2.0.2-py2.py3-none-any.whl (14 kB)
Installing collected packages: xport
Successfully installed xport-2.0.2

In [2]:
# Import required python modules
import pandas as pd
import xport
import numpy as np

In [3]:
# Read SDTM DM SAS Transport XPT file
with open('/content/cdisc/dm.xpt', 'rb') as f:
  df_dm = xport.to_columns(f)
  df_dm2 = pd.DataFrame(df_dm)
df_dm2.head()

,SUBJID,SITEID,AGE,AGEU,DOMAIN,STUDYID,COUNTRY,SEX,USUBJID,ETHNIC,RACE,RFSTDTC,RFENDTC
0,0210-101,0210,88.0,YEARS,DM,ABC-PROJECT-001,INDIA,M,ABC-PROJECT-001-0210-101,NOT HISPANIC OR LATINO,ASIAN,2021-01-13,2023-07-12
1,0210-102,0210,74.0,YEARS,DM,ABC-PROJECT-001,INDIA,M,ABC-PROJECT-001-0210-102,NOT HISPANIC OR LATINO,ASIAN,2021-01-13,2021-01-13
2,0210-103,0210,83.0,YEARS,DM,ABC-PROJECT-001,INDIA,M,ABC-PROJECT-001-0210-103,NOT HISPANIC OR LATINO,ASIAN,2021-02-10,2023-08-16
3,0210-104,0210,81.0,YEARS,DM,ABC-PROJECT-001,INDIA,F,ABC-PROJECT-001-0210-104,NOT HISPANIC OR LATINO,ASIAN,,
4,0210-105,0210,77.0,YEARS,DM,ABC-PROJECT-001,INDIA,M,ABC-PROJECT-001-0210-105,NOT HISPANIC OR LATINO,ASIAN,2021-02-10,2023-08-16

In [4]:
# Create demographic listing
## Select and rename variables
df_dm3 = df_dm2[['SUBJID', 'SEX', 'RACE', 'ETHNIC', 'AGE']].rename(columns={'SUBJID':'Patient ID',
                                                                            'SEX':'Sex', 'RACE':'Race',
                                                                            'ETHNIC':'Ethnicity',
                                                                            'AGE':'Age(year)'})

In [5]:
df_dm3

   Patient ID Sex   Race               Ethnicity  Age(year)
0    0210-101   M  ASIAN  NOT HISPANIC OR LATINO       88.0
1    0210-102   M  ASIAN  NOT HISPANIC OR LATINO       74.0
2    0210-103   M  ASIAN  NOT HISPANIC OR LATINO       83.0
3    0210-104   F  ASIAN  NOT HISPANIC OR LATINO       81.0
4    0210-105   M  ASIAN  NOT HISPANIC OR LATINO       77.0
5    0210-106   M  ASIAN  NOT HISPANIC OR LATINO       75.0
6    0327-101   F  ASIAN  NOT HISPANIC OR LATINO       77.0
7    0327-102   M  ASIAN  NOT HISPANIC OR LATINO       82.0
8    0327-103   F  ASIAN  NOT HISPANIC OR LATINO       75.0
9    0782-101   M  ASIAN  NOT HISPANIC OR LATINO       73.0
10   0802-101   M  ASIAN  NOT HISPANIC OR LATINO       82.0
11   0802-102   M  ASIAN  NOT HISPANIC OR LATINO       75.0
12   0802-103   M  ASIAN  NOT HISPANIC OR LATINO       73.0
13   0802-104   M  ASIAN  NOT HISPANIC OR LATINO       58.0
14   0802-105   M  ASIAN  NOT HISPANIC OR LATINO       67.0
15   0802-106   M  ASIAN  NOT HISPANIC OR LATINO       79.0
16   0816-101   M  ASIAN  NOT HISPANIC OR LATINO       78.0
17   1661-101   M  ASIAN  NOT HISPANIC OR LATINO       64.0
18   1661-102   F  ASIAN  NOT HISPANIC OR LATINO       78.0
19   1662-101   M  ASIAN  NOT HISPANIC OR LATINO       71.0
20   1663-101   M  ASIAN  NOT HISPANIC OR LATINO       83.0
21   1664-101   M  ASIAN  NOT HISPANIC OR LATINO       85.0
22   1664-102   M  ASIAN  NOT HISPANIC OR LATINO       79.0
23   1664-103   M  ASIAN  NOT HISPANIC OR LATINO       74.0
24   1664-104   M  ASIAN  NOT HISPANIC OR LATINO       84.0
25   1667-101   M  ASIAN  NOT HISPANIC OR LATINO       72.0
26   1691-101   M  ASIAN  NOT HISPANIC OR LATINO       77.0
27   1692-101   M  ASIAN  NOT HISPANIC OR LATINO       73.0

In [6]:
# Left alignment of columns
from pandas import DataFrame

def left_align(df_dm3: DataFrame):
    left_aligned_df = df_dm3.style.set_properties(**{'text-align': 'left'})
    left_aligned_df = left_aligned_df.set_table_styles(
        [dict(selector='th', props=[('text-align', 'left')])]
    )
    return left_aligned_df

In [7]:
# Set index variable
df_dmlist = df_dm3.set_index('Patient ID', inplace=False)
left_align(df_dmlist)

In [8]:
from pandas import DataFrame

def left_align(df_dmlist: DataFrame):
    # Apply styling to a copy of the DataFrame
    left_aligned_df = df_dmlist.copy()
    left_aligned_df = left_aligned_df.style.set_properties(**{'text-align': 'left'})
    left_aligned_df = left_aligned_df.set_table_styles(
        [dict(selector='th', props=[('text-align', 'left')])]
    )
    # Return the styled DataFrame for display and the original DataFrame for manipulation
    return left_aligned_df, df_dmlist

# Get the styled df and the original df
df_dmlist_styled, df_dmlist2 = left_align(df_dmlist)

# Display the styled df
df_dmlist_styled

# Save the original df to a CSV file
df_dmlist2.to_csv('Demographic Listing.csv')